Spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:ProductManagement
    driverClassName: org.h2.Driver
    username: sa
    Password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
